#!/usr/bin/env bash

# ==============================================================================
# SCRIPT: harden_secOS.sh
# ARCHETYPE: The Ronin (Offensive-Security Hardening)
# HARDWARE: Raspberry Pi 5 (ARM64)
# OS SUPPORT: Kali Linux / Parrot Security
# DESCRIPTION: Hardens identity and perimeter while preserving offensive capabilities.
#              - Preserves SSH Tunneling (Pivoting)
#              - Sets up "OpMode" aliases for firewall management
#              - Removes default cryptographic identities
#              - Optimizes kernel for stability over paranoia
# Vibed by: Gemini Pro 3
# ==============================================================================

set -eo pipefail

# --- Color Definitions ---
CYAN='\033[0;36m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BOLD='\033[1m'
NC='\033[0m' # No Color

# --- Configuration ---
# Change this if you use a non-standard SSH port for your C2
SSH_PORT="22" 
TARGET_USER="${SUDO_USER:-$(who am i | awk '{print $1}')}"
USER_HOME=$(getent passwd "$TARGET_USER" | cut -d: -f6)

# --- Banner ---
show_banner() {
    clear
    echo -e "${BOLD}${RED}"
    echo "   (    (      (         "
    echo "   )\ ) )\ )   )\ )      "
    echo "  (()/((()/(  (()/( (    "
    echo "   /(_))/(_))  /(_)))\   "
    echo "  (_)) (_))   (_)) ((_)  "
    echo "  | _ \/ __|  | _ \ (_)  "
    echo "  |   /\__ \  |  _/ | |  "
    echo "  |_|_\|___/  |_|   |_|  "
    echo -e "${NC}"
    echo -e "${CYAN}>>> TACTICAL NODE HARDENING INITIATED${NC}"
    echo -e "${CYAN}>>> TARGET: $TARGET_USER ($USER_HOME)${NC}"
    echo -e "${CYAN}>>> MODE:   OFFENSIVE (Pivoting Enabled)${NC}"
    echo ""
    sleep 2
}

# --- 1. Root Check ---
check_root() {
    if [[ $EUID -ne 0 ]]; then
        echo -e "${RED}[!] This script must be run as root.${NC}"
        exit 1
    fi
}

# --- 2. Identity Purge (Anti-Forensics/Anti-Spoofing) ---
purge_identities() {
    echo -e "${YELLOW}[*] Purging factory default SSH host keys...${NC}"
    # Delete the keys generated by the image builder
    rm -f /etc/ssh/ssh_host_*
    
    # Generate new, unique keys for this specific device
    echo -e "${GREEN}[+] Generating fresh ED25519 and RSA keys...${NC}"
    ssh-keygen -t ed25519 -f /etc/ssh/ssh_host_ed25519_key -N "" -q
    ssh-keygen -t rsa -b 4096 -f /etc/ssh/ssh_host_rsa_key -N "" -q
    
    # Regenerate machine-id (optional, but good for uniqueness)
    if [ -f /etc/machine-id ]; then
        rm /etc/machine-id
        systemd-machine-id-setup
        echo -e "${GREEN}[+] Machine ID regenerated.${NC}"
    fi
}

# --- 3. Tactical SSH Configuration (The Pivot Point) ---
# CRITICAL: We enable TCP Forwarding to allow this box to act as a pivot.
secure_ssh() {
    echo -e "${YELLOW}[*] Hardening SSH configuration...${NC}"
    local ssh_config="/etc/ssh/sshd_config"
    
    # Create backup
    cp "$ssh_config" "${ssh_config}.bak"

    # 1. Access Control
    # sed -i 's/^#\?Port .*/Port 2222/' "$ssh_config" # Uncomment if using custom port
    sed -i 's/^#\?PermitRootLogin .*/PermitRootLogin no/' "$ssh_config"
    sed -i 's/^#\?PasswordAuthentication .*/PasswordAuthentication no/' "$ssh_config"
    sed -i 's/^#\?PubkeyAuthentication .*/PubkeyAuthentication yes/' "$ssh_config"
    sed -i 's/^#\?PermitEmptyPasswords .*/PermitEmptyPasswords no/' "$ssh_config"

    # 2. Offensive Capabilities (ENABLED)
    # Allows you to tunnel traffic through this box (Dynamic Port Forwarding)
    sed -i 's/^#\?AllowTcpForwarding .*/AllowTcpForwarding yes/' "$ssh_config"
    sed -i 's/^#\?GatewayPorts .*/GatewayPorts yes/' "$ssh_config"
    # Allows GUI tools (like Burp) to be projected back to you if needed
    sed -i 's/^#\?X11Forwarding .*/X11Forwarding yes/' "$ssh_config"

    # 3. Crypto Hardening (Modern Ciphers Only)
    # Remove old/weak algorithms
    sed -i '/^KexAlgorithms/d' "$ssh_config"
    sed -i '/^Ciphers/d' "$ssh_config"
    sed -i '/^MACs/d' "$ssh_config"

    # Add strong algorithms
    echo "KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha256" >> "$ssh_config"
    echo "Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr" >> "$ssh_config"
    echo "MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com" >> "$ssh_config"

    systemctl restart ssh
    echo -e "${GREEN}[+] SSH hardened. Key-based auth ONLY. Pivoting ENABLED.${NC}"
}

# --- 4. Perimeter Defense (UFW with Tactical Aliases) ---
setup_firewall() {
    echo -e "${YELLOW}[*] configuring UFW Firewall...${NC}"
    apt-get install -y ufw > /dev/null

    # Reset
    ufw --force reset > /dev/null

    # Default Posture: Ghost Mode
    ufw default deny incoming
    ufw default allow outgoing  # Needed for updates & reverse shells

    # Allow Management
    ufw allow "$SSH_PORT"/tcp comment 'SSH Management'

    # Enable
    ufw --force enable
    echo -e "${GREEN}[+] Firewall Active. Default Policy: DENY INCOMING.${NC}"

    # Setup "Game Mode" Aliases
    # These allow you to quickly open listener ports without typing sudo ufw commands constantly
    local bashrc="$USER_HOME/.bashrc"
    local zshrc="$USER_HOME/.zshrc"

    # Define aliases
    read -r -d '' ALIASES << EOM
# --- TACTICAL FIREWALL ALIASES ---
# Open a listener port (e.g., 'listen 4444')
alias listen='sudo ufw allow'
# Close a listener port (e.g., 'shutup 4444')
alias shutup='sudo ufw delete allow'
# Drop shields completely (Use with caution)
alias shieldsdown='sudo ufw default allow incoming'
# Raise shields (Return to safe mode)
alias shieldsup='sudo ufw default deny incoming'
# Check status
alias shields='sudo ufw status numbered'
EOM

    # Inject into .zshrc (Kali Default) and .bashrc
    echo "$ALIASES" >> "$bashrc"
    if [ -f "$zshrc" ]; then
        echo "$ALIASES" >> "$zshrc"
    fi
    
    echo -e "${GREEN}[+] Tactical aliases injected (listen, shutup, shieldsup, shieldsdown).${NC}"
}

# --- 5. Kernel Tuning (Stability > Paranoia) ---
harden_kernel() {
    echo -e "${YELLOW}[*] Applying Kernel parameters...${NC}"
    cat <<EOF > /etc/sysctl.d/99-tactical.conf
# Spoof protection (reverse path filtering)
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1

# Ignore ICMP broadcasts (Smurf attack protection)
net.ipv4.icmp_echo_ignore_broadcasts = 1

# Log Martians (Packets with impossible addresses)
net.ipv4.conf.all.log_martians = 1

# SYN Flood protection
net.ipv4.tcp_syncookies = 1

# Disable IPv6 Redirects (Prevents some MITM)
net.ipv6.conf.all.accept_redirects = 0
net.ipv6.conf.default.accept_redirects = 0

# NOTE: We do NOT disable dmesg or BPF JIT here to preserve debugging capabilities.
EOF
    sysctl -p /etc/sysctl.d/99-tactical.conf > /dev/null
    echo -e "${GREEN}[+] Kernel parameters applied.${NC}"
}

# --- 6. Service Minimization ---
clean_services() {
    echo -e "${YELLOW}[*] Disabling noisy services...${NC}"
    
    # Avahi (mDNS) screams "I AM A LINUX BOX" to the local network. Kill it.
    systemctl stop avahi-daemon 2>/dev/null || true
    systemctl disable avahi-daemon 2>/dev/null || true
    
    # Cups (Printing) - Tactical nodes don't print.
    systemctl stop cups 2>/dev/null || true
    systemctl disable cups 2>/dev/null || true
    
    echo -e "${GREEN}[+] Avahi and CUPS disabled.${NC}"
}

# --- Main Execution ---
main() {
    check_root
    show_banner
    
    purge_identities
    secure_ssh
    clean_services
    setup_firewall
    harden_kernel
    
    echo -e "${BOLD}${GREEN}"
    echo "=================================================="
    echo "   HARDENING COMPLETE"
    echo "=================================================="
    echo -e "${NC}"
    echo "Next Steps:"
    echo "1. Ensure your public key is in $USER_HOME/.ssh/authorized_keys"
    echo "2. Reboot the device: 'sudo reboot'"
    echo "3. Verify access via SSH."
    echo ""
}

main